### PR TITLE
extended public keys: similar terminology

### PR DESCRIPTION
**Pull request by SamouraiDev**

### CODE REVIEW

**Comment by nopara73** [comment]
I really hate to argue on semantics, but I think at this stage we should.  

According to "[Hall Rules and Conventions of Academic Writing](https://drhazelhall.files.wordpress.com/2013/01/2013_hall_rules-conventions_ac_writing.pdf)" dropping the usage of abbreviation would be the right way to go.  
  
I suspect xpub is a more narrow term, because for testnet it is tpub.  
  
I propose the usage of "extended public key".

**Comment by SamouraiDev** [comment]
Sounds good.

**Comment by nopara73** [comment]
I meant use "extended public key" instead of "extpubkey" at every instance.

**Comment by SamouraiDev** [comment]
No change required.,

**Pull request closed without merging**
